sudo: required
language: minimal
services:
- docker
script: "./ci/publish_docker.sh"
branches:
  except:
  - gh-pages
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: rkN8HPqXY8ucFnUmiV7Dv6QxYycI/osCC0OEnQIhtN+ONcWjhCaFDcYINrE8nuQI3kiHL+5z6BrTlMGSebgnistnQGxus+Q9rKfeupKJG9dtW7ecQ0rQ0Jg5hx5F8jqjiOGj1Kw1jObeFuRduZp7o/+Sw78+59Y8lmUTFn/ZivRT4uUKHagBNSkwESH+8GzasTOzySFNc5dJ501sxFPLv7vVXh3G1p8JCcpaYsSsSP+E2eSMWiljbca5fsQdxFq9szUcFt/pFp05vtXVIK3pf2/NDec7ZGpAVujpc4sDAAPBoOrOFjD+h/TlXtRXje1dpQ/0hHDlEHFgssL6u1VRcL8Vn8ixoIPkSXRRgBr8jJYRAFX09Sf7IBdHOAmmDWNbgpi8LBX4kumWAsanjQ6t9qdk76u9RKqspeDIy6L3ks8aq8FR0jSJcg+SPwWAHSgP92aPOmYcywMWHo0FJD/2lylS79kXUPX4RtpeQ/o1qOdwaBs4MJTnmuGnC6KmSIenVK53TIOHxarwdSugobazviW8rTZoObN3ZEksKe/3QPpcy4K1Mntc9+f30nMZI+10EouvpqFSHQOzd41TgvVaF04MZ7BMQR2fSV2tMiX+eI9SM4oLJVoGuzv04fSINXAq36w413VnyX+jWMPkj7Zio/ef3JjJrWuaqanZoQEHlR0=
  - secure: f/qwXtLHH4dKCKTkDNMqfs+LYVrTGysP4je2GXqqtabRfo33W12zEkn5f6SEKfZff74Ta4yYwJpEWyrmBDB67bn+l6PtucgJuWq57CCex/dby9g5PMPSJE+U9kFR3xeE6MLrXrjEcqADdkcriF1PQg1NsttkIEg1nbzxgRjWpc5zZltj5pGtQdM/QSUghkXnviMe0epP3/luJ3X3uYjdavJr6NV9OF+wDSjcmi4hUmnFgctTNscKzn0Q+ChM2ZVnxK867xzuNN6m8jArCFlLHC56a/+DKIDI01iYKW7BYAiLKY5BhMRMLo/14vTYTG+KVgAerXNjJ7WMh+tBLOnDPFIDE2uj4+U7c30ZpaFQcZJiyHTPvYGsz6tlAZhVHWkP8SvTvZe2k6VpSF5hYvy5h9WlbwD/cxuGvACgxCovhTlA9ydImROzPrUJZduQheFnNcvJXXntndkA3ABbSV4ffeQRdhqdaNjkeqMWtB7G8rSt+07eIRzYk6ntlnmqSarCAg0loicCWD1TwSltSMyBODJCNwlJOLPzp/VGXsP++1Kh25mS10/Jr+A70AQk45L1ISTC222ICD20gJAV5gSkwvvgCjhY2QLD932q/iGGyfXE02i7jGTT/KEgFVGGnaBPHTNAovJmgjnnwzVarMcHrqXAJklSZeeeWsGhXPyrlrQ=
